name: pyinstaller

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: "0"

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install pyinstaller
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Create pyinstaller package
        run: |
          pyinstaller main.py

          mv dist/main chess
          cp -r images chess/
          cp config.toml chess/
          mv chess/main chess/chess

          rm -rf build
          rm -rf dist

          mv chess chess-linux
          tar -czvf chess-linux.tar.gz chess-linux

          rm -rf build

      - name: Upload pyinstaller package
        uses: actions/upload-artifact@v2
        with:
          name: pyinstaller-package
          path: chess-linux.tar.gz

      - name: Create pyinstaller executable
        run: |
          pyinstaller main.py

          mv dist chess
          cp -r images chess/
          cp config.toml chess/
          mv chess/main chess/chess

          rm -rf build
          rm -rf dist

          mv chess chess-linux-executable
          tar -czvf chess-linux-executable.tar.gz chess-linux-executable

      - name: Upload pyinstaller executable
        uses: actions/upload-artifact@v2
        with:
          name: pyinstaller-executable
          path: chess-linux-executable.tar.gz

      - name: Create Release
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "*tar.gz"
          bodyFile: "CHANGELOG.md"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Linux Package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: chess-linux.tar.gz
          asset_name: chess-linux.tar.gz
          asset_content_type: application/gzip
